### PR TITLE
Fix Eval stack safety

### LINKED ISSUE #557: Refactor Eval to new stack-safe version
https://github.com/typelevel/cats/pull/1888/files

I just compared implementations with cats and they introduced changes in September to improve stack safety. cc @aedans

### PR DESCRIPTION
**Pull request by aedans**
Fixes #557

### CODE REVIEW

File: arrow-core/src/main/kotlin/arrow/core/Eval.kt [hunk 1]
```diff
@@ -63,6 +63,92 @@ sealed class Eval<out A> : EvalKind<A> {
...
+
+            fun addToMemo(m: Memoize<Any?>): (Any?) -> Eval<Any?> = {
+                m.result = Some(it)
+                now(it)
+            }
+
+            loop@ while (true) {
+                when (curr) {
+                    is FlatMap -> {
+                        val currComp = curr as FlatMap<A>
```
Comment (pakoito) [inline arrow-core/src/main/kotlin/arrow/core/Eval.kt]: Erasure sucks -.-
