### PR TITLE
Fix combining Optional with Traversable

### LINKED ISSUE #620: Combining Optional with Traversable causes stack overflow
To reproduce: https://gist.github.com/jereksel/6b8991b5ecd510e251123a831b1226a0

### PR DESCRIPTION
**Pull request by jereksel**
Fixes #620

### CODE REVIEW

File: arrow-optics/src/test/kotlin/arrow/optics/StackOverflowTest.kt [hunk 1]
```diff
@@ -0,0 +1,98 @@
+package arrow.optics
+
+import arrow.core.Either
+import arrow.data.ListKW
+import arrow.data.ListKWKind
+import arrow.data.k
+import arrow.syntax.either.left
+import arrow.syntax.either.right
+import arrow.test.UnitSpec
+import org.assertj.core.api.Assertions.assertThat
```
Comment (raulraja) [inline arrow-optics/src/test/kotlin/arrow/optics/StackOverflowTest.kt]: Can we use kotlin-test assertions such as `shouldBe` to not add this extra dependency?, Kotlin test is already in the classpath

Comment (jereksel) [reply arrow-optics/src/test/kotlin/arrow/optics/StackOverflowTest.kt]: Done

**Comment by pakoito** [comment]
Good job. Cheers for finding it ^^
