### PR TITLE
[#153] Control NonFatal Throwables

### LINKED ISSUE #153: Allow `NonFatal` control over exceptions for MonadError and Monadic comprehensions
Currently comprehending over Try in an stack unsafe way returns a `Failures(SOE)` we should never capture fatal exceptions. See for reference http://www.scala-lang.org/api/2.12.0/scala/util/control/NonFatal$.html

### PR DESCRIPTION
**Pull request by kartoffelsup**
As discussed in https://kotlinlang.slack.com/archives/C5UPMM0A0/p1550319070097800
Port of the Scala NonFatal.

I've hopefully found all places where it should be applied. I've searched with `catch \(.*:\s+Throwable\)` in all Production Files using IntelliJ.

Closes #153

### CODE REVIEW

File: modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt [hunk 1]
```diff
@@ -36,7 +43,11 @@ interface ApplicativeError<F, E> : Applicative<F> {
     try {
       just(f())
     } catch (t: Throwable) {
-      raiseError<A>(recover(t))
+      if (NonFatal(t)) {
```
Comment (raulraja) [inline modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: We can encapsulate this pattern For All `ApplicativeError<F>` which constitutes most of the changes in this PR.
If you place this function as part of the MonadThrow<F> type class
```kotlin
fun <F, A> Throwable.raiseNonFatal(): Kind<F, A> =
  if (NonFatal(this)) raiseError<A>(this) else throw e
```

This functions is scoped to the MonadThrow receiver and will be available in all instances of all the data types as extension functions and would allow you to remove the if else boilerplate in most cases below.

File: modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/IOBracket.kt [hunk 2]
```diff
@@ -61,7 +62,11 @@ internal object IOBracket {
               val fb = try {
                 use(a)
               } catch (e: Throwable) {
-                IO.raiseError<B>(e)
+                if (NonFatal(e)) {
```
Comment (raulraja) [inline modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/internal/IOBracket.kt]: `e.raiseNonFatal()`

File: modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Async.kt [hunk 3]
```diff
@@ -142,7 +143,11 @@ interface Async<F> : MonadDefer<F> {
       try {
         just(f())
       } catch (t: Throwable) {
-        raiseError<A>(t)
+        if (NonFatal(t)) {
```
Comment (raulraja) [inline modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/Async.kt]: `t.raiseNonFatal()`

File: modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt [hunk 4]
```diff
@@ -25,7 +26,11 @@ interface MonadDefer<F> : MonadThrow<F>, Bracket<F, Throwable> {
       try {
         just(f())
       } catch (t: Throwable) {
-        raiseError<A>(t)
+        if (NonFatal(t)) {
```
Comment (raulraja) [inline modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt]: `t.raiseNonFatal()`

File: modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt [hunk 5]
```diff
@@ -38,7 +43,11 @@ interface MonadDefer<F> : MonadThrow<F>, Bracket<F, Throwable> {
...
```
Comment (raulraja) [inline modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDefer.kt]: `t.raiseNonFatal()`

File: modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDeferCancellableContinuations.kt [hunk 6]
```diff
@@ -59,7 +60,11 @@ open class MonadDeferCancellableContinuation<F, A>(val SC: MonadDefer<F>, overri
       val datatype = try {
         just(m())
       } catch (t: Throwable) {
-        raiseError<B>(t)
+        if (NonFatal(t)) {
```
Comment (raulraja) [inline modules/effects/arrow-effects-data/src/main/kotlin/arrow/effects/typeclasses/MonadDeferCancellableContinuations.kt]: `t.raiseNonFatal()`

File: modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt (hunk 1 above)
Comment (kartoffelsup) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: Thanks for the review and the great suggestion. :) I've applied it to all but IOBracket, it didn't work there (I guess because it's not running in the MonadThrow context?)

There is also a AbstractMethodError in `IOTest MonadDefer bind: binding failure` that I can't quite figure out.

Comment (pakoito) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: Change the genError code to throw something else instead, maybe that's the issue. I'd add a new generator that throws one of the fatal errors and test for that.

Comment (kartoffelsup) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: After updating graalvm to rc12 (my jdk), the test no longer fails.
Should I add the fatal error test to MonadDefer laws?

Comment (pakoito) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: I'd add a MonadThrow laws altogether that have all MonadErrorLaws, put that test in them, and make MonadDefer do MonadThrowLaws instead of MonadErrorLaws.

That way we have tests where the functions are defined in the hierarchy :D

Comment (kartoffelsup) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: Mmh, does this test even work inside MonadThrow? There is no delay/defer that actually does a try {} catch {} or am I missing something?

Comment (pakoito) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: Then the function should live in MonadDefer :D @raulraja opinions?

Comment (raulraja) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: The function can be expressed in `MonadThrow` and override `catch` to use it:
```kotlin
override fun <A> catch(recover: (Throwable) -> Throwable, f: () -> A): Kind<F, A> 
override fun <A> ApplicativeError<F, Throwable>.catch(f: () -> A): Kind<F, A> 
```
It has application outside suspensions of effects given the loose approach we take with `Try` at the moment. This is an example of a datatype that would benefit from it and that does not allow suspension and can't implement MonadDefer. Another one would be Either for partially applied Throwables.
IMO it should live in `MonadThrow`.

Comment (kartoffelsup) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: Sorry, I'm kind of lost now. :D I've added the suggested function `raiseNonFatal` to MonadThrow.
What else can I do? (and how can I/should I test it as MonadThrow Law?)

Comment (raulraja) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: @kartoffelsup this should cover it:

- override the two functions above using `raiseNonFatal` to implement them in `MonadThrow`
- Add a new law in the `arrow.test.laws.MonadErrorLaws` 
> Monad Error Laws: NonFatal is caught
- Add a new la  in the `arrow.test.laws.MonadErrorLaws` 
> Monad Error Laws: Fatal errors are thrown
- Add kdoc and a `kotlin:ank:playground` snippet similar to the one in `Functor` that illustrates the usage of NonFatal in the `NonFatal` object.

That should do it.

Comment (kartoffelsup) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: @raulraja thanks for the guidance!
Regarding the catch overrides, atm I've already overridden them in ApplicativeError like so:
```kotlin
 fun <A> catch(recover: (Throwable) -> E, f: () -> A): Kind<F, A> =
    try {
      just(f())
    } catch (t: Throwable) {
      if (NonFatal(t)) {
        raiseError<A>(recover(t))
      } else {
        throw t
      }
    }

  fun <A> ApplicativeError<F, Throwable>.catch(f: () -> A): Kind<F, A> =
    catch(::identity, f)
```
Do we really need the override in MonadThrow? 
Also, it looks to me that the `catch(recover: (Throwable) -> E, f: () -> A)` variant can't be done with `raiseNonFatal` as I am unable to call `#map` on it for the `recover` function.

Comment (raulraja) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: no, if you already did it there it's fine how you did it.

Comment (kartoffelsup) [reply modules/core/arrow-typeclasses/src/main/kotlin/arrow/typeclasses/ApplicativeError.kt]: I've applied the changes you requested. Please let me know if there is anything else I can do. Thanks again for the help!

**Comment by raulraja** [comment]
Looks like reactor Flowable is not stack safe https://app.bitrise.io/build/73c812fbc6ef9620.
Can you decrease that number.
You can check the docs run by running `./gradlew clean dokka :arrow-docs:runAnk`

**Comment by raulraja** [comment]
I'll rerun the build and if it passes we will leave that for another PR

**Comment by raulraja** [comment]
@pakoito any idea what is going on here and why this has not surfaced before? https://app.bitrise.io/build/288ec840d3cdc0ca

**Comment by pakoito** [comment]
None of the Rx constructs are stack-safe.

**Comment by kartoffelsup** [comment]
Looks like that is intended there? https://arrow-kt.io/docs/integrations/rx2/#stack-safety, the comment above states this is what's supposed to happen. But the StackOverflow was caught previously.
