### PR TITLE
`validate` for `Either`

### LINKED ISSUE #3639: ["Request"] Analogue of Either.recover for turning right values into left values
What version are you currently using?
`2.1.2`

What would you like to see?

I have frequently found myself reaching for an ergonomic way to examine the results of a call that returns an Either, and in some additional additional situations turn a right value into a left value.

This is common when using things like Either.catch { } on an http connector or a database call, where a value might not have led to an exception, but could still be invalid for the business logic of the application, and should be remapped into a business error after being recognized. Similarly so, if you are combining multiple Eithers that might have been successes on their own, but when some combination of them comes back, there are additional validations can be done.

I know this can be achieved by binding the Eithers within a Raise context, but particularly with code that is returning an Either is often more convenient to continue along in chaining rather than switching to the Raise DSL. At least for now, public functions returning Eithers are more discoverable through autocomplete than Raise equivalents.

The closest equivalent to what I have found myself reaching for is the 'recover' function, able to continue chaining on an Either and examine a failure, and either propagate it, transform it, or turn it into a success.

With credit to @kyay10 for both helping with current ways to accomplish this action in the current version of Arrow, and for prototyping solutions.

Toy sample code that might benefit from this is here:

```
fun randomNumber(): Either<String, Int> {
    val randomNum = Random(1).nextInt(1..10)

    return if (randomNum > 5) {
        randomNum.right()
    } else {
        "The number was too low".left()
    }
}

fun failOnMoreConditionsFlatmap(): Either<String, Int> {
    return randomNumber()
        .flatMap { num ->
           either {
               ensure(num != 10) { "Number 10 also not allowed" }
               num
           }
    }
}

fun failOnMoreConditionsBind(): Either<String, Int> = either {
  randomNumber().bind().also {
    ensure(it != 10) { "Number 10 also not allowed" }
  }
}.map { it + 100 }
```

whereas the ability to deal with a similar situation through recover requires less nesting, as there's no need to create a raise dsl through an inline `either`

```
fun recoverExample(): Either<String, Int> {
    return randomNumber()
        .recover {
            val recoveryAttempt = Random(2).nextInt(1..10)
            ensure(recoveryAttempt > 5) { "tried to recover and failed" }
            recoveryAttempt
        }
        .map { it + 100 }
}
```

A solution was suggested by @kyay10 on slack

```
inline fun <A, E, B> Either<E, A>.bindMap(transform: Raise<E>.(A) -> B): Either<E, B> = either { transform(bind()) }
```

that would create the raise context automatically, allowing remapping the at the same time as raising, with less nesting than the current version. This seems like it could situationally be very useful. Following the toy example it could be used like

```
fun failOnMoreConditionsWithBindMap(): Either<String, Int> =
    randomNumber().bindMap { number ->
        ensure(number != 10) { "Number 10 also not allowed" }
        number
    }.map { it + 100 }
```
or even
```
fun failOnMoreConditionsWithBindMapAndRemap(): Either<String, String> =
    randomNumber().bindMap { number ->
        ensure(number != 10) { "Number 10 also not allowed" }
        (number + 100).toString()
    }
```

I think my original request probably comes from a place looking for a more limited version of that, that would treat the additional raises as the only possible effect of the call, which could be implemented using the above as something like the below: (name could be improved)

```
public inline fun <E, A> Either<E, A>.checkForRaises(transform: Raise<E>.(A) -> Unit): Either<E, A> =
    this.bindMap {
        transform(it)
        it
    }
```

and used as
```
fun failOnMoreConditionsWithCheckForRaises(): Either<String, Int> =
    randomNumber().checkForRaises { number ->
        ensure(number != 10) { "Number 10 also not allowed" }
    }.map { it + 100 }
```

See [slack conversation on this here](https://kotlinlang.slack.com/archives/C5UPMM0A0/p1749516143585309)

### PR DESCRIPTION
**Pull request by serras**
Fixes #3639
Closes #3711

This is the result of the discussion in #3711 (it was easier for me to create a new PR than to rollback all the changes there). This PR introduces a single `validate` function that runs a `Raise` block on `Right` values, but leaves them unchanged until something `raise`s. This seems quite effective in combination with `ensure` to write one-liners:

```kotlin
fun failOnMoreConditionsWithBindMap(): Either<String, Int> =
    randomNumber()
        .validate { ensure(it != 10) { "Number 10 also not allowed" } }
        .map { it + 100 }
```

### CODE REVIEW

File: arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt [hunk 1]
```diff
@@ -772,6 +772,32 @@ public sealed class Either<out A, out B> {
...
+   *   val zero: Either<String, Int> = Either.Right(0)
+   *   zero.validate { ensure(it > 0) { "negative" } } shouldBe Either.Left("negative")
+   * }
+   * ```
+   * <!--- KNIT example-either-32.kt -->
+   * <!--- TEST lines.isEmpty() -->
+   */
+  public fun validate(validation: Raise<@UnsafeVariance A>.(B) -> Unit): Either<A, B> = when (this) {
+    is Left -> this
+    is Right -> either { validation(value) ; value }
```
Comment (tKe) [inline arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt]: Very minor, but we could avoid creating new `Right` by using fold directly:

```suggestion
    is Right -> fold({ validation(value) }, { Left(it) }, { this })
```

Comment (kyay10) [reply arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt]: This should probably be `inline`

**Review by kyay10 — APPROVED** [review]
