### PR TITLE
Remove ObservableK Traverse/MonadFilter instances as they're not lawful. 

### LINKED ISSUE #1881: [Bug] rx2 MonadFilter instances are not lawful in the presence of errors
Uncovered by #1877 

Specifically the right empty law does not hold because `flatMap` in the presence of errors will short-circuit. Not sure how this should be handled.

### LINKED ISSUE #1882: [Bug] rx2 Traverse/Foldable instances are not lawful
Uncovered by #1877 

For `ObservableK` and `FlowableK` foldable is implemented using `blockingGet`. Not too familiar with those types but isn't that equal to `unsafeRunSync` in terms of semantics? Either way this fails when given errors and rightly so. We should remove those instances, they are not lawful. We could keep the combinators, but definitly not as part of `Foldable` or `Traversable`.

### PR DESCRIPTION
**Pull request by aballano**
As @1Jajen1 mentioned, ObservableK does foldable by using `blockingGet` which essentially is a `unsafeRunSync()`.

Fixes #1882.

--

Similarly for MonadFilter instances, Observable has the notion of errors, therefore the laws won't pass right now because an error + empty states will output an error, which is not considered in such laws.

Fixes #1881.

### CODE REVIEW

File: modules/core/arrow-test/src/main/kotlin/arrow/test/laws/TraverseLaws.kt [hunk 1]
```diff
@@ -47,17 +47,6 @@ class TIF {
 }
 
 object TraverseLaws {
-  // FIXME(paco): this implementation will crash the inliner. Wait for fix: https://youtrack.jetbrains.com/issue/KT-18660
```
Comment (aballano) [inline modules/core/arrow-test/src/main/kotlin/arrow/test/laws/TraverseLaws.kt]: @pakoito hope is ok to remove this, or shall we refactor it somehow?

File: modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt [hunk 2]
```diff
@@ -303,11 +286,9 @@ interface ObservableKFunctorFilter : FunctorFilter<ForObservableK>, ObservableKF
...
 
-@extension
-interface ObservableKMonadFilter : MonadFilter<ForObservableK>, ObservableKMonad {
-  override fun <A> empty(): ObservableK<A> =
-    Observable.empty<A>().k()
-
-  override fun <A, B> Kind<ForObservableK, A>.filterMap(f: (A) -> Option<B>): ObservableK<B> =
-    fix().filterMap(f)
-}
+// TODO Could be revisited in the future. Right now it fails to pass the laws due to the notion of errors.
```
Comment (raulraja) [inline modules/fx/arrow-fx-rx2/src/main/kotlin/arrow/fx/rx2/extensions/observablek.kt]: This should be just removed since we are not deprecating it. Observable will never be able to support this with the current encoding we have for MTL based on subtypes.

File: modules/core/arrow-test/src/main/kotlin/arrow/test/laws/TraverseLaws.kt (hunk 1 above)
Comment (pakoito) [reply modules/core/arrow-test/src/main/kotlin/arrow/test/laws/TraverseLaws.kt]: The original bug is fixed, maybe it's worth bringing it back.
