### PR TITLE
fix imports for ksp plugin

### LINKED ISSUE #2618: KSP Optics plugin does not consider imports
The following does not compile:

```kotlin
import arrow.optics.optics
import kotlin.time.Duration

@optics
data class OpticsTest(
    val time: Duration
) {
    companion object
}
```

because the generated code lacks the required `kotlin.time.Duration` import:

```kotlin
import arrow.core.left
import arrow.core.right
import arrow.core.toOption

inline val OpticsTest.Companion.iso: arrow.optics.Iso<OpticsTest, Duration> inline get()= arrow.optics.Iso(
  get = { opticsTest: OpticsTest -> opticsTest.time },
  reverseGet = { OpticsTest(it) }
)

inline val OpticsTest.Companion.time: arrow.optics.Lens<OpticsTest, Duration> inline get()= arrow.optics.Lens(
  get = { opticsTest: OpticsTest -> opticsTest.`time` },
  set = { opticsTest: OpticsTest, value: Duration -> opticsTest.copy(`time` = value) }
)



inline val <S> arrow.optics.Iso<S, OpticsTest>.time: arrow.optics.Lens<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Lens<S, OpticsTest>.time: arrow.optics.Lens<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Optional<S, OpticsTest>.time: arrow.optics.Optional<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Prism<S, OpticsTest>.time: arrow.optics.Optional<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Getter<S, OpticsTest>.time: arrow.optics.Getter<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Setter<S, OpticsTest>.time: arrow.optics.Setter<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Traversal<S, OpticsTest>.time: arrow.optics.Traversal<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Fold<S, OpticsTest>.time: arrow.optics.Fold<S, Duration> inline get() = this + OpticsTest.time
inline val <S> arrow.optics.Every<S, OpticsTest>.time: arrow.optics.Every<S, Duration> inline get() = this + OpticsTest.time
```

### PR DESCRIPTION
**Pull request by i-walker**
resolves #2618 
Status:
**In progres**

### CODE REVIEW

File: arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt [hunk 1]
```diff
@@ -4,11 +4,10 @@ import com.google.devtools.ksp.symbol.KSClassDeclaration
 import com.google.devtools.ksp.symbol.KSName
 import java.util.Locale
 
-data class ADT(val pckg: KSName, val el: KSClassDeclaration, val targets: List<Target>) {
-  val sourceClassName = el.qualifiedName?.asString() ?: el.simpleName
-  val sourceName = el.simpleName.asString().replaceFirstChar { it.lowercase(Locale.getDefault()) }
-  val simpleName = el.simpleName.asString()
-  val packageName = pckg.asString()
```
Comment (nomisRev) [inline arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt:11]: Can we keep these names the same? This is our own domain.
This introduces a lot of unnecessary changes in the PR.

File: arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt [hunk 2]
```diff
@@ -20,12 +20,22 @@ private fun String.toUpperCamelCase(): String =
...
-  |inline val ${ele.sourceClassName}.Companion.${focus.lensParamName()}: $Lens<${ele.sourceClassName}, ${focus.className}> inline get()= $Lens(
-  |  get = { ${ele.sourceName}: ${ele.sourceClassName} -> ${ele.sourceName}.${focus.paramName.plusIfNotBlank(prefix = "`", postfix = "`")} },
-  |  set = { ${ele.sourceName}: ${ele.sourceClassName}, value: ${focus.className} -> ${ele.sourceName}.copy(${focus.paramName.plusIfNotBlank(prefix = "`", postfix = "`")} = value) }
+  |inline val ${adt.qualifiedNameOrSimpleName}.Companion.${focus.lensParamName()}: $Lens<${adt.qualifiedNameOrSimpleName}, ${focus.className}> inline get()= $Lens(
+  |  get = { ${adt.simpleName}: ${adt.qualifiedNameOrSimpleName} -> ${adt.simpleName}.${
+      focus.paramName.plusIfNotBlank(
+        prefix = "`",
+        postfix = "`"
+      )
+    } },
```
Comment (nomisRev) [inline arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt:32]: I think this change is incorrect, since it's not prefixed with `|`

File: arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt [hunk 3]
```diff
@@ -38,7 +38,6 @@ class LensTests {
   fun `Lenses which mentions imported elements`() {
     """
       |$imports
-      |import kotlin.time.Duration
```
Comment (nomisRev) [inline arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt:41]: These tests were not running if this bug was not caught. Is it possible to make them run?
If this import is removed, then it should be using FQN on line 47.

**Review by nomisRev — CHANGES_REQUESTED** [review]

File: arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt (hunk 2 above)
Comment (i-walker) [reply arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/lenses.kt:32]: This one is still within the ‘${}’ so this is just formatting

File: arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt (hunk 1 above)
Comment (i-walker) [reply arrow-libs/optics/arrow-optics-ksp-plugin/src/main/kotlin/arrow/optics/plugin/internals/domain.kt:11]: Sure

File: arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt (hunk 3 above)
Comment (i-walker) [reply arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt:41]: Was removed since I added a variable in the dslModel with a Duration type so the import is automatically added in $import

Comment (i-walker) [reply arrow-libs/optics/arrow-optics-ksp-plugin/src/test/kotlin/arrow/optics/plugin/LensTests.kt:41]: Let me change those to FQNames instead ☺️

**Review by nomisRev — APPROVED** [review]
Looks great @i-walker! Thanks for the work on the fix ❤️
